// Code generated by go-swagger; DO NOT EDIT.

package home

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteZoneOverlayParams creates a new DeleteZoneOverlayParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteZoneOverlayParams() *DeleteZoneOverlayParams {
	return &DeleteZoneOverlayParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteZoneOverlayParamsWithTimeout creates a new DeleteZoneOverlayParams object
// with the ability to set a timeout on a request.
func NewDeleteZoneOverlayParamsWithTimeout(timeout time.Duration) *DeleteZoneOverlayParams {
	return &DeleteZoneOverlayParams{
		timeout: timeout,
	}
}

// NewDeleteZoneOverlayParamsWithContext creates a new DeleteZoneOverlayParams object
// with the ability to set a context for a request.
func NewDeleteZoneOverlayParamsWithContext(ctx context.Context) *DeleteZoneOverlayParams {
	return &DeleteZoneOverlayParams{
		Context: ctx,
	}
}

// NewDeleteZoneOverlayParamsWithHTTPClient creates a new DeleteZoneOverlayParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteZoneOverlayParamsWithHTTPClient(client *http.Client) *DeleteZoneOverlayParams {
	return &DeleteZoneOverlayParams{
		HTTPClient: client,
	}
}

/* DeleteZoneOverlayParams contains all the parameters to send to the API endpoint
   for the delete zone overlay operation.

   Typically these are written to a http.Request.
*/
type DeleteZoneOverlayParams struct {

	/* HomeID.

	   The ID of a home.

	   Format: int64
	*/
	HomeID int64

	/* ZoneID.

	   The ID of a zone.

	   Format: int64
	*/
	ZoneID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete zone overlay params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteZoneOverlayParams) WithDefaults() *DeleteZoneOverlayParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete zone overlay params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteZoneOverlayParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete zone overlay params
func (o *DeleteZoneOverlayParams) WithTimeout(timeout time.Duration) *DeleteZoneOverlayParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete zone overlay params
func (o *DeleteZoneOverlayParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete zone overlay params
func (o *DeleteZoneOverlayParams) WithContext(ctx context.Context) *DeleteZoneOverlayParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete zone overlay params
func (o *DeleteZoneOverlayParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete zone overlay params
func (o *DeleteZoneOverlayParams) WithHTTPClient(client *http.Client) *DeleteZoneOverlayParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete zone overlay params
func (o *DeleteZoneOverlayParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHomeID adds the homeID to the delete zone overlay params
func (o *DeleteZoneOverlayParams) WithHomeID(homeID int64) *DeleteZoneOverlayParams {
	o.SetHomeID(homeID)
	return o
}

// SetHomeID adds the homeId to the delete zone overlay params
func (o *DeleteZoneOverlayParams) SetHomeID(homeID int64) {
	o.HomeID = homeID
}

// WithZoneID adds the zoneID to the delete zone overlay params
func (o *DeleteZoneOverlayParams) WithZoneID(zoneID int64) *DeleteZoneOverlayParams {
	o.SetZoneID(zoneID)
	return o
}

// SetZoneID adds the zoneId to the delete zone overlay params
func (o *DeleteZoneOverlayParams) SetZoneID(zoneID int64) {
	o.ZoneID = zoneID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteZoneOverlayParams) WriteToRequest(r runtime.ClientRequest, _ strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param home_id
	if err := r.SetPathParam("home_id", swag.FormatInt64(o.HomeID)); err != nil {
		return err
	}

	// path param zone_id
	if err := r.SetPathParam("zone_id", swag.FormatInt64(o.ZoneID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
