// Code generated by go-swagger; DO NOT EDIT.

package home

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/gonzolino/gotado/api/models"
)

// HomeStateReader is a Reader for the HomeState structure.
type HomeStateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HomeStateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewHomeStateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewHomeStateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewHomeStateForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewHomeStateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewHomeStateOK creates a HomeStateOK with default headers values
func NewHomeStateOK() *HomeStateOK {
	return &HomeStateOK{}
}

/* HomeStateOK describes a response with status code 200, with default header values.

Home State
*/
type HomeStateOK struct {
	Payload *models.HomeState
}

func (o *HomeStateOK) Error() string {
	return fmt.Sprintf("[GET /homes/{home_id}/state][%d] homeStateOK  %+v", 200, o.Payload)
}
func (o *HomeStateOK) GetPayload() *models.HomeState {
	return o.Payload
}

func (o *HomeStateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, _ strfmt.Registry) error {

	o.Payload = new(models.HomeState)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewHomeStateUnauthorized creates a HomeStateUnauthorized with default headers values
func NewHomeStateUnauthorized() *HomeStateUnauthorized {
	return &HomeStateUnauthorized{}
}

/* HomeStateUnauthorized describes a response with status code 401, with default header values.

User authentication failed.
*/
type HomeStateUnauthorized struct {
	Payload *models.ClientErrorModel
}

func (o *HomeStateUnauthorized) Error() string {
	return fmt.Sprintf("[GET /homes/{home_id}/state][%d] homeStateUnauthorized  %+v", 401, o.Payload)
}
func (o *HomeStateUnauthorized) GetPayload() *models.ClientErrorModel {
	return o.Payload
}

func (o *HomeStateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, _ strfmt.Registry) error {

	o.Payload = new(models.ClientErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewHomeStateForbidden creates a HomeStateForbidden with default headers values
func NewHomeStateForbidden() *HomeStateForbidden {
	return &HomeStateForbidden{}
}

/* HomeStateForbidden describes a response with status code 403, with default header values.

Authenticated user has no access rights to the requested entity.
*/
type HomeStateForbidden struct {
	Payload *models.ClientErrorModel
}

func (o *HomeStateForbidden) Error() string {
	return fmt.Sprintf("[GET /homes/{home_id}/state][%d] homeStateForbidden  %+v", 403, o.Payload)
}
func (o *HomeStateForbidden) GetPayload() *models.ClientErrorModel {
	return o.Payload
}

func (o *HomeStateForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, _ strfmt.Registry) error {

	o.Payload = new(models.ClientErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewHomeStateNotFound creates a HomeStateNotFound with default headers values
func NewHomeStateNotFound() *HomeStateNotFound {
	return &HomeStateNotFound{}
}

/* HomeStateNotFound describes a response with status code 404, with default header values.

Requested entity not found.
*/
type HomeStateNotFound struct {
	Payload *models.ClientErrorModel
}

func (o *HomeStateNotFound) Error() string {
	return fmt.Sprintf("[GET /homes/{home_id}/state][%d] homeStateNotFound  %+v", 404, o.Payload)
}
func (o *HomeStateNotFound) GetPayload() *models.ClientErrorModel {
	return o.Payload
}

func (o *HomeStateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, _ strfmt.Registry) error {

	o.Payload = new(models.ClientErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
