// Code generated by go-swagger; DO NOT EDIT.

package home

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewHomeStateParams creates a new HomeStateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewHomeStateParams() *HomeStateParams {
	return &HomeStateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewHomeStateParamsWithTimeout creates a new HomeStateParams object
// with the ability to set a timeout on a request.
func NewHomeStateParamsWithTimeout(timeout time.Duration) *HomeStateParams {
	return &HomeStateParams{
		timeout: timeout,
	}
}

// NewHomeStateParamsWithContext creates a new HomeStateParams object
// with the ability to set a context for a request.
func NewHomeStateParamsWithContext(ctx context.Context) *HomeStateParams {
	return &HomeStateParams{
		Context: ctx,
	}
}

// NewHomeStateParamsWithHTTPClient creates a new HomeStateParams object
// with the ability to set a custom HTTPClient for a request.
func NewHomeStateParamsWithHTTPClient(client *http.Client) *HomeStateParams {
	return &HomeStateParams{
		HTTPClient: client,
	}
}

/* HomeStateParams contains all the parameters to send to the API endpoint
   for the home state operation.

   Typically these are written to a http.Request.
*/
type HomeStateParams struct {

	/* HomeID.

	   The ID of a home.

	   Format: int64
	*/
	HomeID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the home state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HomeStateParams) WithDefaults() *HomeStateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the home state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HomeStateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the home state params
func (o *HomeStateParams) WithTimeout(timeout time.Duration) *HomeStateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the home state params
func (o *HomeStateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the home state params
func (o *HomeStateParams) WithContext(ctx context.Context) *HomeStateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the home state params
func (o *HomeStateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the home state params
func (o *HomeStateParams) WithHTTPClient(client *http.Client) *HomeStateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the home state params
func (o *HomeStateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHomeID adds the homeID to the home state params
func (o *HomeStateParams) WithHomeID(homeID int64) *HomeStateParams {
	o.SetHomeID(homeID)
	return o
}

// SetHomeID adds the homeId to the home state params
func (o *HomeStateParams) SetHomeID(homeID int64) {
	o.HomeID = homeID
}

// WriteToRequest writes these params to a swagger request
func (o *HomeStateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param home_id
	if err := r.SetPathParam("home_id", swag.FormatInt64(o.HomeID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
