// Code generated by go-swagger; DO NOT EDIT.

package home

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/gonzolino/gotado/api/models"
)

// ListZonesReader is a Reader for the ListZones structure.
type ListZonesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListZonesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListZonesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListZonesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListZonesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListZonesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListZonesOK creates a ListZonesOK with default headers values
func NewListZonesOK() *ListZonesOK {
	return &ListZonesOK{}
}

/* ListZonesOK describes a response with status code 200, with default header values.

List of zones
*/
type ListZonesOK struct {
	Payload []*models.Zone
}

func (o *ListZonesOK) Error() string {
	return fmt.Sprintf("[GET /homes/{home_id}/zones][%d] listZonesOK  %+v", 200, o.Payload)
}
func (o *ListZonesOK) GetPayload() []*models.Zone {
	return o.Payload
}

func (o *ListZonesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListZonesUnauthorized creates a ListZonesUnauthorized with default headers values
func NewListZonesUnauthorized() *ListZonesUnauthorized {
	return &ListZonesUnauthorized{}
}

/* ListZonesUnauthorized describes a response with status code 401, with default header values.

User authentication failed.
*/
type ListZonesUnauthorized struct {
	Payload *models.ClientErrorModel
}

func (o *ListZonesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /homes/{home_id}/zones][%d] listZonesUnauthorized  %+v", 401, o.Payload)
}
func (o *ListZonesUnauthorized) GetPayload() *models.ClientErrorModel {
	return o.Payload
}

func (o *ListZonesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClientErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListZonesForbidden creates a ListZonesForbidden with default headers values
func NewListZonesForbidden() *ListZonesForbidden {
	return &ListZonesForbidden{}
}

/* ListZonesForbidden describes a response with status code 403, with default header values.

Authenticated user has no access rights to the requested entity.
*/
type ListZonesForbidden struct {
	Payload *models.ClientErrorModel
}

func (o *ListZonesForbidden) Error() string {
	return fmt.Sprintf("[GET /homes/{home_id}/zones][%d] listZonesForbidden  %+v", 403, o.Payload)
}
func (o *ListZonesForbidden) GetPayload() *models.ClientErrorModel {
	return o.Payload
}

func (o *ListZonesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClientErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListZonesNotFound creates a ListZonesNotFound with default headers values
func NewListZonesNotFound() *ListZonesNotFound {
	return &ListZonesNotFound{}
}

/* ListZonesNotFound describes a response with status code 404, with default header values.

Requested entity not found.
*/
type ListZonesNotFound struct {
	Payload *models.ClientErrorModel
}

func (o *ListZonesNotFound) Error() string {
	return fmt.Sprintf("[GET /homes/{home_id}/zones][%d] listZonesNotFound  %+v", 404, o.Payload)
}
func (o *ListZonesNotFound) GetPayload() *models.ClientErrorModel {
	return o.Payload
}

func (o *ListZonesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClientErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
