// Code generated by go-swagger; DO NOT EDIT.

package home

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/gonzolino/gotado/api/models"
)

// ListMobileDevicesReader is a Reader for the ListMobileDevices structure.
type ListMobileDevicesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListMobileDevicesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListMobileDevicesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListMobileDevicesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListMobileDevicesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListMobileDevicesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListMobileDevicesOK creates a ListMobileDevicesOK with default headers values
func NewListMobileDevicesOK() *ListMobileDevicesOK {
	return &ListMobileDevicesOK{}
}

/* ListMobileDevicesOK describes a response with status code 200, with default header values.

(Potentially empty) list of mobile devices associated with this home.
*/
type ListMobileDevicesOK struct {
	Payload []*models.MobileDevice
}

func (o *ListMobileDevicesOK) Error() string {
	return fmt.Sprintf("[GET /homes/{home_id}/mobileDevices][%d] listMobileDevicesOK  %+v", 200, o.Payload)
}
func (o *ListMobileDevicesOK) GetPayload() []*models.MobileDevice {
	return o.Payload
}

func (o *ListMobileDevicesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, _ strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListMobileDevicesUnauthorized creates a ListMobileDevicesUnauthorized with default headers values
func NewListMobileDevicesUnauthorized() *ListMobileDevicesUnauthorized {
	return &ListMobileDevicesUnauthorized{}
}

/* ListMobileDevicesUnauthorized describes a response with status code 401, with default header values.

User authentication failed.
*/
type ListMobileDevicesUnauthorized struct {
	Payload *models.ClientErrorModel
}

func (o *ListMobileDevicesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /homes/{home_id}/mobileDevices][%d] listMobileDevicesUnauthorized  %+v", 401, o.Payload)
}
func (o *ListMobileDevicesUnauthorized) GetPayload() *models.ClientErrorModel {
	return o.Payload
}

func (o *ListMobileDevicesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, _ strfmt.Registry) error {

	o.Payload = new(models.ClientErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListMobileDevicesForbidden creates a ListMobileDevicesForbidden with default headers values
func NewListMobileDevicesForbidden() *ListMobileDevicesForbidden {
	return &ListMobileDevicesForbidden{}
}

/* ListMobileDevicesForbidden describes a response with status code 403, with default header values.

Authenticated user has no access rights to the requested entity.
*/
type ListMobileDevicesForbidden struct {
	Payload *models.ClientErrorModel
}

func (o *ListMobileDevicesForbidden) Error() string {
	return fmt.Sprintf("[GET /homes/{home_id}/mobileDevices][%d] listMobileDevicesForbidden  %+v", 403, o.Payload)
}
func (o *ListMobileDevicesForbidden) GetPayload() *models.ClientErrorModel {
	return o.Payload
}

func (o *ListMobileDevicesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, _ strfmt.Registry) error {

	o.Payload = new(models.ClientErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListMobileDevicesNotFound creates a ListMobileDevicesNotFound with default headers values
func NewListMobileDevicesNotFound() *ListMobileDevicesNotFound {
	return &ListMobileDevicesNotFound{}
}

/* ListMobileDevicesNotFound describes a response with status code 404, with default header values.

Requested entity not found.
*/
type ListMobileDevicesNotFound struct {
	Payload *models.ClientErrorModel
}

func (o *ListMobileDevicesNotFound) Error() string {
	return fmt.Sprintf("[GET /homes/{home_id}/mobileDevices][%d] listMobileDevicesNotFound  %+v", 404, o.Payload)
}
func (o *ListMobileDevicesNotFound) GetPayload() *models.ClientErrorModel {
	return o.Payload
}

func (o *ListMobileDevicesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, _ strfmt.Registry) error {

	o.Payload = new(models.ClientErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
