// Code generated by go-swagger; DO NOT EDIT.

package home

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListZonesParams creates a new ListZonesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListZonesParams() *ListZonesParams {
	return &ListZonesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListZonesParamsWithTimeout creates a new ListZonesParams object
// with the ability to set a timeout on a request.
func NewListZonesParamsWithTimeout(timeout time.Duration) *ListZonesParams {
	return &ListZonesParams{
		timeout: timeout,
	}
}

// NewListZonesParamsWithContext creates a new ListZonesParams object
// with the ability to set a context for a request.
func NewListZonesParamsWithContext(ctx context.Context) *ListZonesParams {
	return &ListZonesParams{
		Context: ctx,
	}
}

// NewListZonesParamsWithHTTPClient creates a new ListZonesParams object
// with the ability to set a custom HTTPClient for a request.
func NewListZonesParamsWithHTTPClient(client *http.Client) *ListZonesParams {
	return &ListZonesParams{
		HTTPClient: client,
	}
}

/* ListZonesParams contains all the parameters to send to the API endpoint
   for the list zones operation.

   Typically these are written to a http.Request.
*/
type ListZonesParams struct {

	/* HomeID.

	   The ID of a home.

	   Format: int64
	*/
	HomeID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list zones params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListZonesParams) WithDefaults() *ListZonesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list zones params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListZonesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list zones params
func (o *ListZonesParams) WithTimeout(timeout time.Duration) *ListZonesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list zones params
func (o *ListZonesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list zones params
func (o *ListZonesParams) WithContext(ctx context.Context) *ListZonesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list zones params
func (o *ListZonesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list zones params
func (o *ListZonesParams) WithHTTPClient(client *http.Client) *ListZonesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list zones params
func (o *ListZonesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHomeID adds the homeID to the list zones params
func (o *ListZonesParams) WithHomeID(homeID int64) *ListZonesParams {
	o.SetHomeID(homeID)
	return o
}

// SetHomeID adds the homeId to the list zones params
func (o *ListZonesParams) SetHomeID(homeID int64) {
	o.HomeID = homeID
}

// WriteToRequest writes these params to a swagger request
func (o *ListZonesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param home_id
	if err := r.SetPathParam("home_id", swag.FormatInt64(o.HomeID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
