// Code generated by go-swagger; DO NOT EDIT.

package home

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/gonzolino/gotado/api/models"
)

// ShowHomeReader is a Reader for the ShowHome structure.
type ShowHomeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ShowHomeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewShowHomeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewShowHomeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewShowHomeForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewShowHomeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewShowHomeOK creates a ShowHomeOK with default headers values
func NewShowHomeOK() *ShowHomeOK {
	return &ShowHomeOK{}
}

/* ShowHomeOK describes a response with status code 200, with default header values.

Home details
*/
type ShowHomeOK struct {
	Payload *models.HomeInfo
}

func (o *ShowHomeOK) Error() string {
	return fmt.Sprintf("[GET /homes/{home_id}][%d] showHomeOK  %+v", 200, o.Payload)
}
func (o *ShowHomeOK) GetPayload() *models.HomeInfo {
	return o.Payload
}

func (o *ShowHomeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HomeInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewShowHomeUnauthorized creates a ShowHomeUnauthorized with default headers values
func NewShowHomeUnauthorized() *ShowHomeUnauthorized {
	return &ShowHomeUnauthorized{}
}

/* ShowHomeUnauthorized describes a response with status code 401, with default header values.

User authentication failed.
*/
type ShowHomeUnauthorized struct {
	Payload *models.ClientErrorModel
}

func (o *ShowHomeUnauthorized) Error() string {
	return fmt.Sprintf("[GET /homes/{home_id}][%d] showHomeUnauthorized  %+v", 401, o.Payload)
}
func (o *ShowHomeUnauthorized) GetPayload() *models.ClientErrorModel {
	return o.Payload
}

func (o *ShowHomeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClientErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewShowHomeForbidden creates a ShowHomeForbidden with default headers values
func NewShowHomeForbidden() *ShowHomeForbidden {
	return &ShowHomeForbidden{}
}

/* ShowHomeForbidden describes a response with status code 403, with default header values.

Authenticated user has no access rights to the requested entity.
*/
type ShowHomeForbidden struct {
	Payload *models.ClientErrorModel
}

func (o *ShowHomeForbidden) Error() string {
	return fmt.Sprintf("[GET /homes/{home_id}][%d] showHomeForbidden  %+v", 403, o.Payload)
}
func (o *ShowHomeForbidden) GetPayload() *models.ClientErrorModel {
	return o.Payload
}

func (o *ShowHomeForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClientErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewShowHomeNotFound creates a ShowHomeNotFound with default headers values
func NewShowHomeNotFound() *ShowHomeNotFound {
	return &ShowHomeNotFound{}
}

/* ShowHomeNotFound describes a response with status code 404, with default header values.

Requested entity not found.
*/
type ShowHomeNotFound struct {
	Payload *models.ClientErrorModel
}

func (o *ShowHomeNotFound) Error() string {
	return fmt.Sprintf("[GET /homes/{home_id}][%d] showHomeNotFound  %+v", 404, o.Payload)
}
func (o *ShowHomeNotFound) GetPayload() *models.ClientErrorModel {
	return o.Payload
}

func (o *ShowHomeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClientErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
