// Code generated by go-swagger; DO NOT EDIT.

package home

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewShowZoneCapabilitiesParams creates a new ShowZoneCapabilitiesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewShowZoneCapabilitiesParams() *ShowZoneCapabilitiesParams {
	return &ShowZoneCapabilitiesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewShowZoneCapabilitiesParamsWithTimeout creates a new ShowZoneCapabilitiesParams object
// with the ability to set a timeout on a request.
func NewShowZoneCapabilitiesParamsWithTimeout(timeout time.Duration) *ShowZoneCapabilitiesParams {
	return &ShowZoneCapabilitiesParams{
		timeout: timeout,
	}
}

// NewShowZoneCapabilitiesParamsWithContext creates a new ShowZoneCapabilitiesParams object
// with the ability to set a context for a request.
func NewShowZoneCapabilitiesParamsWithContext(ctx context.Context) *ShowZoneCapabilitiesParams {
	return &ShowZoneCapabilitiesParams{
		Context: ctx,
	}
}

// NewShowZoneCapabilitiesParamsWithHTTPClient creates a new ShowZoneCapabilitiesParams object
// with the ability to set a custom HTTPClient for a request.
func NewShowZoneCapabilitiesParamsWithHTTPClient(client *http.Client) *ShowZoneCapabilitiesParams {
	return &ShowZoneCapabilitiesParams{
		HTTPClient: client,
	}
}

/* ShowZoneCapabilitiesParams contains all the parameters to send to the API endpoint
   for the show zone capabilities operation.

   Typically these are written to a http.Request.
*/
type ShowZoneCapabilitiesParams struct {

	/* HomeID.

	   The ID of a home.

	   Format: int64
	*/
	HomeID int64

	/* ZoneID.

	   The ID of a zone.

	   Format: int64
	*/
	ZoneID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the show zone capabilities params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ShowZoneCapabilitiesParams) WithDefaults() *ShowZoneCapabilitiesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the show zone capabilities params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ShowZoneCapabilitiesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the show zone capabilities params
func (o *ShowZoneCapabilitiesParams) WithTimeout(timeout time.Duration) *ShowZoneCapabilitiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the show zone capabilities params
func (o *ShowZoneCapabilitiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the show zone capabilities params
func (o *ShowZoneCapabilitiesParams) WithContext(ctx context.Context) *ShowZoneCapabilitiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the show zone capabilities params
func (o *ShowZoneCapabilitiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the show zone capabilities params
func (o *ShowZoneCapabilitiesParams) WithHTTPClient(client *http.Client) *ShowZoneCapabilitiesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the show zone capabilities params
func (o *ShowZoneCapabilitiesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHomeID adds the homeID to the show zone capabilities params
func (o *ShowZoneCapabilitiesParams) WithHomeID(homeID int64) *ShowZoneCapabilitiesParams {
	o.SetHomeID(homeID)
	return o
}

// SetHomeID adds the homeId to the show zone capabilities params
func (o *ShowZoneCapabilitiesParams) SetHomeID(homeID int64) {
	o.HomeID = homeID
}

// WithZoneID adds the zoneID to the show zone capabilities params
func (o *ShowZoneCapabilitiesParams) WithZoneID(zoneID int64) *ShowZoneCapabilitiesParams {
	o.SetZoneID(zoneID)
	return o
}

// SetZoneID adds the zoneId to the show zone capabilities params
func (o *ShowZoneCapabilitiesParams) SetZoneID(zoneID int64) {
	o.ZoneID = zoneID
}

// WriteToRequest writes these params to a swagger request
func (o *ShowZoneCapabilitiesParams) WriteToRequest(r runtime.ClientRequest, _ strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param home_id
	if err := r.SetPathParam("home_id", swag.FormatInt64(o.HomeID)); err != nil {
		return err
	}

	// path param zone_id
	if err := r.SetPathParam("zone_id", swag.FormatInt64(o.ZoneID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
