// Code generated by go-swagger; DO NOT EDIT.

package home

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/gonzolino/gotado/api/models"
)

// ShowZoneStateReader is a Reader for the ShowZoneState structure.
type ShowZoneStateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ShowZoneStateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewShowZoneStateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewShowZoneStateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewShowZoneStateForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewShowZoneStateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewShowZoneStateOK creates a ShowZoneStateOK with default headers values
func NewShowZoneStateOK() *ShowZoneStateOK {
	return &ShowZoneStateOK{}
}

/* ShowZoneStateOK describes a response with status code 200, with default header values.

Zone state.
*/
type ShowZoneStateOK struct {
	Payload *models.ZoneState
}

func (o *ShowZoneStateOK) Error() string {
	return fmt.Sprintf("[GET /homes/{home_id}/zones/{zone_id}/state][%d] showZoneStateOK  %+v", 200, o.Payload)
}
func (o *ShowZoneStateOK) GetPayload() *models.ZoneState {
	return o.Payload
}

func (o *ShowZoneStateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, _ strfmt.Registry) error {

	o.Payload = new(models.ZoneState)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewShowZoneStateUnauthorized creates a ShowZoneStateUnauthorized with default headers values
func NewShowZoneStateUnauthorized() *ShowZoneStateUnauthorized {
	return &ShowZoneStateUnauthorized{}
}

/* ShowZoneStateUnauthorized describes a response with status code 401, with default header values.

User authentication failed.
*/
type ShowZoneStateUnauthorized struct {
	Payload *models.ClientErrorModel
}

func (o *ShowZoneStateUnauthorized) Error() string {
	return fmt.Sprintf("[GET /homes/{home_id}/zones/{zone_id}/state][%d] showZoneStateUnauthorized  %+v", 401, o.Payload)
}
func (o *ShowZoneStateUnauthorized) GetPayload() *models.ClientErrorModel {
	return o.Payload
}

func (o *ShowZoneStateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, _ strfmt.Registry) error {

	o.Payload = new(models.ClientErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewShowZoneStateForbidden creates a ShowZoneStateForbidden with default headers values
func NewShowZoneStateForbidden() *ShowZoneStateForbidden {
	return &ShowZoneStateForbidden{}
}

/* ShowZoneStateForbidden describes a response with status code 403, with default header values.

Authenticated user has no access rights to the requested entity.
*/
type ShowZoneStateForbidden struct {
	Payload *models.ClientErrorModel
}

func (o *ShowZoneStateForbidden) Error() string {
	return fmt.Sprintf("[GET /homes/{home_id}/zones/{zone_id}/state][%d] showZoneStateForbidden  %+v", 403, o.Payload)
}
func (o *ShowZoneStateForbidden) GetPayload() *models.ClientErrorModel {
	return o.Payload
}

func (o *ShowZoneStateForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, _ strfmt.Registry) error {

	o.Payload = new(models.ClientErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewShowZoneStateNotFound creates a ShowZoneStateNotFound with default headers values
func NewShowZoneStateNotFound() *ShowZoneStateNotFound {
	return &ShowZoneStateNotFound{}
}

/* ShowZoneStateNotFound describes a response with status code 404, with default header values.

Requested entity not found.
*/
type ShowZoneStateNotFound struct {
	Payload *models.ClientErrorModel
}

func (o *ShowZoneStateNotFound) Error() string {
	return fmt.Sprintf("[GET /homes/{home_id}/zones/{zone_id}/state][%d] showZoneStateNotFound  %+v", 404, o.Payload)
}
func (o *ShowZoneStateNotFound) GetPayload() *models.ClientErrorModel {
	return o.Payload
}

func (o *ShowZoneStateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, _ strfmt.Registry) error {

	o.Payload = new(models.ClientErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
