// Code generated by go-swagger; DO NOT EDIT.

package home

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/gonzolino/gotado/api/models"
)

// ShowUserReader is a Reader for the ShowUser structure.
type ShowUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ShowUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewShowUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewShowUserUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewShowUserOK creates a ShowUserOK with default headers values
func NewShowUserOK() *ShowUserOK {
	return &ShowUserOK{}
}

/* ShowUserOK describes a response with status code 200, with default header values.

User details
*/
type ShowUserOK struct {
	Payload *models.User
}

func (o *ShowUserOK) Error() string {
	return fmt.Sprintf("[GET /me][%d] showUserOK  %+v", 200, o.Payload)
}
func (o *ShowUserOK) GetPayload() *models.User {
	return o.Payload
}

func (o *ShowUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.User)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewShowUserUnauthorized creates a ShowUserUnauthorized with default headers values
func NewShowUserUnauthorized() *ShowUserUnauthorized {
	return &ShowUserUnauthorized{}
}

/* ShowUserUnauthorized describes a response with status code 401, with default header values.

User authentication failed.
*/
type ShowUserUnauthorized struct {
	Payload *models.ClientErrorModel
}

func (o *ShowUserUnauthorized) Error() string {
	return fmt.Sprintf("[GET /me][%d] showUserUnauthorized  %+v", 401, o.Payload)
}
func (o *ShowUserUnauthorized) GetPayload() *models.ClientErrorModel {
	return o.Payload
}

func (o *ShowUserUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClientErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
