// Code generated by go-swagger; DO NOT EDIT.

package home

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/gonzolino/gotado/api/models"
)

// ShowZoneDefaultOverlayReader is a Reader for the ShowZoneDefaultOverlay structure.
type ShowZoneDefaultOverlayReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ShowZoneDefaultOverlayReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewShowZoneDefaultOverlayOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewShowZoneDefaultOverlayUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewShowZoneDefaultOverlayForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewShowZoneDefaultOverlayNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewShowZoneDefaultOverlayOK creates a ShowZoneDefaultOverlayOK with default headers values
func NewShowZoneDefaultOverlayOK() *ShowZoneDefaultOverlayOK {
	return &ShowZoneDefaultOverlayOK{}
}

/* ShowZoneDefaultOverlayOK describes a response with status code 200, with default header values.

Preferences for default overlay.
*/
type ShowZoneDefaultOverlayOK struct {
	Payload *models.OverlayTemplate
}

func (o *ShowZoneDefaultOverlayOK) Error() string {
	return fmt.Sprintf("[GET /homes/{home_id}/zones/{zone_id}/defaultOverlay][%d] showZoneDefaultOverlayOK  %+v", 200, o.Payload)
}
func (o *ShowZoneDefaultOverlayOK) GetPayload() *models.OverlayTemplate {
	return o.Payload
}

func (o *ShowZoneDefaultOverlayOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, _ strfmt.Registry) error {

	o.Payload = new(models.OverlayTemplate)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewShowZoneDefaultOverlayUnauthorized creates a ShowZoneDefaultOverlayUnauthorized with default headers values
func NewShowZoneDefaultOverlayUnauthorized() *ShowZoneDefaultOverlayUnauthorized {
	return &ShowZoneDefaultOverlayUnauthorized{}
}

/* ShowZoneDefaultOverlayUnauthorized describes a response with status code 401, with default header values.

User authentication failed.
*/
type ShowZoneDefaultOverlayUnauthorized struct {
	Payload *models.ClientErrorModel
}

func (o *ShowZoneDefaultOverlayUnauthorized) Error() string {
	return fmt.Sprintf("[GET /homes/{home_id}/zones/{zone_id}/defaultOverlay][%d] showZoneDefaultOverlayUnauthorized  %+v", 401, o.Payload)
}
func (o *ShowZoneDefaultOverlayUnauthorized) GetPayload() *models.ClientErrorModel {
	return o.Payload
}

func (o *ShowZoneDefaultOverlayUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, _ strfmt.Registry) error {

	o.Payload = new(models.ClientErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewShowZoneDefaultOverlayForbidden creates a ShowZoneDefaultOverlayForbidden with default headers values
func NewShowZoneDefaultOverlayForbidden() *ShowZoneDefaultOverlayForbidden {
	return &ShowZoneDefaultOverlayForbidden{}
}

/* ShowZoneDefaultOverlayForbidden describes a response with status code 403, with default header values.

Authenticated user has no access rights to the requested entity.
*/
type ShowZoneDefaultOverlayForbidden struct {
	Payload *models.ClientErrorModel
}

func (o *ShowZoneDefaultOverlayForbidden) Error() string {
	return fmt.Sprintf("[GET /homes/{home_id}/zones/{zone_id}/defaultOverlay][%d] showZoneDefaultOverlayForbidden  %+v", 403, o.Payload)
}
func (o *ShowZoneDefaultOverlayForbidden) GetPayload() *models.ClientErrorModel {
	return o.Payload
}

func (o *ShowZoneDefaultOverlayForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, _ strfmt.Registry) error {

	o.Payload = new(models.ClientErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewShowZoneDefaultOverlayNotFound creates a ShowZoneDefaultOverlayNotFound with default headers values
func NewShowZoneDefaultOverlayNotFound() *ShowZoneDefaultOverlayNotFound {
	return &ShowZoneDefaultOverlayNotFound{}
}

/* ShowZoneDefaultOverlayNotFound describes a response with status code 404, with default header values.

Requested entity not found.
*/
type ShowZoneDefaultOverlayNotFound struct {
	Payload *models.ClientErrorModel
}

func (o *ShowZoneDefaultOverlayNotFound) Error() string {
	return fmt.Sprintf("[GET /homes/{home_id}/zones/{zone_id}/defaultOverlay][%d] showZoneDefaultOverlayNotFound  %+v", 404, o.Payload)
}
func (o *ShowZoneDefaultOverlayNotFound) GetPayload() *models.ClientErrorModel {
	return o.Payload
}

func (o *ShowZoneDefaultOverlayNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, _ strfmt.Registry) error {

	o.Payload = new(models.ClientErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
