// Code generated by go-swagger; DO NOT EDIT.

package home

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewShowUserParams creates a new ShowUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewShowUserParams() *ShowUserParams {
	return &ShowUserParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewShowUserParamsWithTimeout creates a new ShowUserParams object
// with the ability to set a timeout on a request.
func NewShowUserParamsWithTimeout(timeout time.Duration) *ShowUserParams {
	return &ShowUserParams{
		timeout: timeout,
	}
}

// NewShowUserParamsWithContext creates a new ShowUserParams object
// with the ability to set a context for a request.
func NewShowUserParamsWithContext(ctx context.Context) *ShowUserParams {
	return &ShowUserParams{
		Context: ctx,
	}
}

// NewShowUserParamsWithHTTPClient creates a new ShowUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewShowUserParamsWithHTTPClient(client *http.Client) *ShowUserParams {
	return &ShowUserParams{
		HTTPClient: client,
	}
}

/* ShowUserParams contains all the parameters to send to the API endpoint
   for the show user operation.

   Typically these are written to a http.Request.
*/
type ShowUserParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the show user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ShowUserParams) WithDefaults() *ShowUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the show user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ShowUserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the show user params
func (o *ShowUserParams) WithTimeout(timeout time.Duration) *ShowUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the show user params
func (o *ShowUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the show user params
func (o *ShowUserParams) WithContext(ctx context.Context) *ShowUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the show user params
func (o *ShowUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the show user params
func (o *ShowUserParams) WithHTTPClient(client *http.Client) *ShowUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the show user params
func (o *ShowUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ShowUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
