// Code generated by go-swagger; DO NOT EDIT.

package home

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewShowHomeParams creates a new ShowHomeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewShowHomeParams() *ShowHomeParams {
	return &ShowHomeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewShowHomeParamsWithTimeout creates a new ShowHomeParams object
// with the ability to set a timeout on a request.
func NewShowHomeParamsWithTimeout(timeout time.Duration) *ShowHomeParams {
	return &ShowHomeParams{
		timeout: timeout,
	}
}

// NewShowHomeParamsWithContext creates a new ShowHomeParams object
// with the ability to set a context for a request.
func NewShowHomeParamsWithContext(ctx context.Context) *ShowHomeParams {
	return &ShowHomeParams{
		Context: ctx,
	}
}

// NewShowHomeParamsWithHTTPClient creates a new ShowHomeParams object
// with the ability to set a custom HTTPClient for a request.
func NewShowHomeParamsWithHTTPClient(client *http.Client) *ShowHomeParams {
	return &ShowHomeParams{
		HTTPClient: client,
	}
}

/* ShowHomeParams contains all the parameters to send to the API endpoint
   for the show home operation.

   Typically these are written to a http.Request.
*/
type ShowHomeParams struct {

	/* HomeID.

	   The ID of a home.

	   Format: int64
	*/
	HomeID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the show home params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ShowHomeParams) WithDefaults() *ShowHomeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the show home params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ShowHomeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the show home params
func (o *ShowHomeParams) WithTimeout(timeout time.Duration) *ShowHomeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the show home params
func (o *ShowHomeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the show home params
func (o *ShowHomeParams) WithContext(ctx context.Context) *ShowHomeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the show home params
func (o *ShowHomeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the show home params
func (o *ShowHomeParams) WithHTTPClient(client *http.Client) *ShowHomeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the show home params
func (o *ShowHomeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHomeID adds the homeID to the show home params
func (o *ShowHomeParams) WithHomeID(homeID int64) *ShowHomeParams {
	o.SetHomeID(homeID)
	return o
}

// SetHomeID adds the homeId to the show home params
func (o *ShowHomeParams) SetHomeID(homeID int64) {
	o.HomeID = homeID
}

// WriteToRequest writes these params to a swagger request
func (o *ShowHomeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param home_id
	if err := r.SetPathParam("home_id", swag.FormatInt64(o.HomeID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
