// Code generated by go-swagger; DO NOT EDIT.

package home

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/gonzolino/gotado/api/models"
)

// UpdateZoneOverlayReader is a Reader for the UpdateZoneOverlay structure.
type UpdateZoneOverlayReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateZoneOverlayReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateZoneOverlayOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateZoneOverlayBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUpdateZoneOverlayUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateZoneOverlayForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateZoneOverlayNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewUpdateZoneOverlayUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateZoneOverlayOK creates a UpdateZoneOverlayOK with default headers values
func NewUpdateZoneOverlayOK() *UpdateZoneOverlayOK {
	return &UpdateZoneOverlayOK{}
}

/* UpdateZoneOverlayOK describes a response with status code 200, with default header values.

Zone overlay.
*/
type UpdateZoneOverlayOK struct {
	Payload *models.Overlay
}

func (o *UpdateZoneOverlayOK) Error() string {
	return fmt.Sprintf("[PUT /homes/{home_id}/zones/{zone_id}/overlay][%d] updateZoneOverlayOK  %+v", 200, o.Payload)
}
func (o *UpdateZoneOverlayOK) GetPayload() *models.Overlay {
	return o.Payload
}

func (o *UpdateZoneOverlayOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, _ strfmt.Registry) error {

	o.Payload = new(models.Overlay)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateZoneOverlayBadRequest creates a UpdateZoneOverlayBadRequest with default headers values
func NewUpdateZoneOverlayBadRequest() *UpdateZoneOverlayBadRequest {
	return &UpdateZoneOverlayBadRequest{}
}

/* UpdateZoneOverlayBadRequest describes a response with status code 400, with default header values.

Bad request, wrong type of parameters, etc.
*/
type UpdateZoneOverlayBadRequest struct {
	Payload *models.ClientErrorModel
}

func (o *UpdateZoneOverlayBadRequest) Error() string {
	return fmt.Sprintf("[PUT /homes/{home_id}/zones/{zone_id}/overlay][%d] updateZoneOverlayBadRequest  %+v", 400, o.Payload)
}
func (o *UpdateZoneOverlayBadRequest) GetPayload() *models.ClientErrorModel {
	return o.Payload
}

func (o *UpdateZoneOverlayBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, _ strfmt.Registry) error {

	o.Payload = new(models.ClientErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateZoneOverlayUnauthorized creates a UpdateZoneOverlayUnauthorized with default headers values
func NewUpdateZoneOverlayUnauthorized() *UpdateZoneOverlayUnauthorized {
	return &UpdateZoneOverlayUnauthorized{}
}

/* UpdateZoneOverlayUnauthorized describes a response with status code 401, with default header values.

User authentication failed.
*/
type UpdateZoneOverlayUnauthorized struct {
	Payload *models.ClientErrorModel
}

func (o *UpdateZoneOverlayUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /homes/{home_id}/zones/{zone_id}/overlay][%d] updateZoneOverlayUnauthorized  %+v", 401, o.Payload)
}
func (o *UpdateZoneOverlayUnauthorized) GetPayload() *models.ClientErrorModel {
	return o.Payload
}

func (o *UpdateZoneOverlayUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, _ strfmt.Registry) error {

	o.Payload = new(models.ClientErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateZoneOverlayForbidden creates a UpdateZoneOverlayForbidden with default headers values
func NewUpdateZoneOverlayForbidden() *UpdateZoneOverlayForbidden {
	return &UpdateZoneOverlayForbidden{}
}

/* UpdateZoneOverlayForbidden describes a response with status code 403, with default header values.

Authenticated user has no access rights to the requested entity.
*/
type UpdateZoneOverlayForbidden struct {
	Payload *models.ClientErrorModel
}

func (o *UpdateZoneOverlayForbidden) Error() string {
	return fmt.Sprintf("[PUT /homes/{home_id}/zones/{zone_id}/overlay][%d] updateZoneOverlayForbidden  %+v", 403, o.Payload)
}
func (o *UpdateZoneOverlayForbidden) GetPayload() *models.ClientErrorModel {
	return o.Payload
}

func (o *UpdateZoneOverlayForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, _ strfmt.Registry) error {

	o.Payload = new(models.ClientErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateZoneOverlayNotFound creates a UpdateZoneOverlayNotFound with default headers values
func NewUpdateZoneOverlayNotFound() *UpdateZoneOverlayNotFound {
	return &UpdateZoneOverlayNotFound{}
}

/* UpdateZoneOverlayNotFound describes a response with status code 404, with default header values.

Requested entity not found.
*/
type UpdateZoneOverlayNotFound struct {
	Payload *models.ClientErrorModel
}

func (o *UpdateZoneOverlayNotFound) Error() string {
	return fmt.Sprintf("[PUT /homes/{home_id}/zones/{zone_id}/overlay][%d] updateZoneOverlayNotFound  %+v", 404, o.Payload)
}
func (o *UpdateZoneOverlayNotFound) GetPayload() *models.ClientErrorModel {
	return o.Payload
}

func (o *UpdateZoneOverlayNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, _ strfmt.Registry) error {

	o.Payload = new(models.ClientErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateZoneOverlayUnprocessableEntity creates a UpdateZoneOverlayUnprocessableEntity with default headers values
func NewUpdateZoneOverlayUnprocessableEntity() *UpdateZoneOverlayUnprocessableEntity {
	return &UpdateZoneOverlayUnprocessableEntity{}
}

/* UpdateZoneOverlayUnprocessableEntity describes a response with status code 422, with default header values.

The request was well-formed but was unable to be followed due to semantic errors.
*/
type UpdateZoneOverlayUnprocessableEntity struct {
	Payload *models.ClientErrorModel
}

func (o *UpdateZoneOverlayUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /homes/{home_id}/zones/{zone_id}/overlay][%d] updateZoneOverlayUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *UpdateZoneOverlayUnprocessableEntity) GetPayload() *models.ClientErrorModel {
	return o.Payload
}

func (o *UpdateZoneOverlayUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, _ strfmt.Registry) error {

	o.Payload = new(models.ClientErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
