// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ActivityDataPoints activity data points
//
// swagger:model ActivityDataPoints
type ActivityDataPoints struct {

	// ac power
	AcPower *AcPowerDataPoint `json:"acPower,omitempty"`

	// heating power
	HeatingPower *PercentageDataPoint `json:"heatingPower,omitempty"`
}

// Validate validates this activity data points
func (m *ActivityDataPoints) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAcPower(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHeatingPower(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ActivityDataPoints) validateAcPower(formats strfmt.Registry) error {
	if swag.IsZero(m.AcPower) { // not required
		return nil
	}

	if m.AcPower != nil {
		if err := m.AcPower.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("acPower")
			}
			return err
		}
	}

	return nil
}

func (m *ActivityDataPoints) validateHeatingPower(formats strfmt.Registry) error {
	if swag.IsZero(m.HeatingPower) { // not required
		return nil
	}

	if m.HeatingPower != nil {
		if err := m.HeatingPower.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("heatingPower")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this activity data points based on the context it is used
func (m *ActivityDataPoints) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAcPower(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateHeatingPower(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ActivityDataPoints) contextValidateAcPower(ctx context.Context, formats strfmt.Registry) error {

	if m.AcPower != nil {
		if err := m.AcPower.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("acPower")
			}
			return err
		}
	}

	return nil
}

func (m *ActivityDataPoints) contextValidateHeatingPower(ctx context.Context, formats strfmt.Registry) error {

	if m.HeatingPower != nil {
		if err := m.HeatingPower.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("heatingPower")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ActivityDataPoints) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ActivityDataPoints) UnmarshalBinary(b []byte) error {
	var res ActivityDataPoints
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
