// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CoolingZoneSetting cooling zone setting
//
// swagger:model CoolingZoneSetting
type CoolingZoneSetting struct {

	// The desired fan speed, if power is `ON` and fan speeds are supported in this AC mode.
	FanSpeed AcFanSpeed `json:"fanSpeed,omitempty"`

	// The desired AC mode, if power is `ON`.
	Mode AcMode `json:"mode,omitempty"`

	// Whether the AC should be ON or OFF.
	// Required: true
	Power *Power `json:"power"`

	// Whether the angle of the air stream should be fixed or not, if power is `ON` and configuring this is supported in this AC mode.
	Swing Power `json:"swing,omitempty"`

	// The desired temperature, if power is `ON` and temperatures are supported in this AC mode.
	Temperature *TemperatureObject `json:"temperature,omitempty"`
}

// Type gets the type of this subtype
func (m *CoolingZoneSetting) Type() TadoSystemType {
	return "CoolingZoneSetting"
}

// SetType sets the type of this subtype
func (m *CoolingZoneSetting) SetType(_ TadoSystemType) {
}

// UnmarshalJSON unmarshals this object with a polymorphic type from a JSON structure
func (m *CoolingZoneSetting) UnmarshalJSON(raw []byte) error {
	var data struct {

		// The desired fan speed, if power is `ON` and fan speeds are supported in this AC mode.
		FanSpeed AcFanSpeed `json:"fanSpeed,omitempty"`

		// The desired AC mode, if power is `ON`.
		Mode AcMode `json:"mode,omitempty"`

		// Whether the AC should be ON or OFF.
		// Required: true
		Power *Power `json:"power"`

		// Whether the angle of the air stream should be fixed or not, if power is `ON` and configuring this is supported in this AC mode.
		Swing Power `json:"swing,omitempty"`

		// The desired temperature, if power is `ON` and temperatures are supported in this AC mode.
		Temperature *TemperatureObject `json:"temperature,omitempty"`
	}
	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	var base struct {
		/* Just the base type fields. Used for unmashalling polymorphic types.*/

		Type TadoSystemType `json:"type"`
	}
	buf = bytes.NewBuffer(raw)
	dec = json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&base); err != nil {
		return err
	}

	var result CoolingZoneSetting

	if base.Type != result.Type() {
		/* Not the type we're looking for. */
		return errors.New(422, "invalid type value: %q", base.Type)
	}

	result.FanSpeed = data.FanSpeed
	result.Mode = data.Mode
	result.Power = data.Power
	result.Swing = data.Swing
	result.Temperature = data.Temperature

	*m = result

	return nil
}

// MarshalJSON marshals this object with a polymorphic type to a JSON structure
func (m CoolingZoneSetting) MarshalJSON() ([]byte, error) {
	var b1, b2, b3 []byte
	var err error
	b1, err = json.Marshal(struct {

		// The desired fan speed, if power is `ON` and fan speeds are supported in this AC mode.
		FanSpeed AcFanSpeed `json:"fanSpeed,omitempty"`

		// The desired AC mode, if power is `ON`.
		Mode AcMode `json:"mode,omitempty"`

		// Whether the AC should be ON or OFF.
		// Required: true
		Power *Power `json:"power"`

		// Whether the angle of the air stream should be fixed or not, if power is `ON` and configuring this is supported in this AC mode.
		Swing Power `json:"swing,omitempty"`

		// The desired temperature, if power is `ON` and temperatures are supported in this AC mode.
		Temperature *TemperatureObject `json:"temperature,omitempty"`
	}{

		FanSpeed: m.FanSpeed,

		Mode: m.Mode,

		Power: m.Power,

		Swing: m.Swing,

		Temperature: m.Temperature,
	})
	if err != nil {
		return nil, err
	}
	b2, err = json.Marshal(struct {
		Type TadoSystemType `json:"type"`
	}{

		Type: m.Type(),
	})
	if err != nil {
		return nil, err
	}

	return swag.ConcatJSON(b1, b2, b3), nil
}

// Validate validates this cooling zone setting
func (m *CoolingZoneSetting) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFanSpeed(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePower(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSwing(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTemperature(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CoolingZoneSetting) validateFanSpeed(formats strfmt.Registry) error {

	if swag.IsZero(m.FanSpeed) { // not required
		return nil
	}

	if err := m.FanSpeed.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("fanSpeed")
		}
		return err
	}

	return nil
}

func (m *CoolingZoneSetting) validateMode(formats strfmt.Registry) error {

	if swag.IsZero(m.Mode) { // not required
		return nil
	}

	if err := m.Mode.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("mode")
		}
		return err
	}

	return nil
}

func (m *CoolingZoneSetting) validatePower(formats strfmt.Registry) error {

	if err := validate.Required("power", "body", m.Power); err != nil {
		return err
	}

	if err := validate.Required("power", "body", m.Power); err != nil {
		return err
	}

	if m.Power != nil {
		if err := m.Power.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("power")
			}
			return err
		}
	}

	return nil
}

func (m *CoolingZoneSetting) validateSwing(formats strfmt.Registry) error {

	if swag.IsZero(m.Swing) { // not required
		return nil
	}

	if err := m.Swing.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("swing")
		}
		return err
	}

	return nil
}

func (m *CoolingZoneSetting) validateTemperature(formats strfmt.Registry) error {

	if swag.IsZero(m.Temperature) { // not required
		return nil
	}

	if m.Temperature != nil {
		if err := m.Temperature.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("temperature")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this cooling zone setting based on the context it is used
func (m *CoolingZoneSetting) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFanSpeed(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMode(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePower(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSwing(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTemperature(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CoolingZoneSetting) contextValidateType(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Type().ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("type")
		}
		return err
	}

	return nil
}

func (m *CoolingZoneSetting) contextValidateFanSpeed(ctx context.Context, formats strfmt.Registry) error {

	if err := m.FanSpeed.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("fanSpeed")
		}
		return err
	}

	return nil
}

func (m *CoolingZoneSetting) contextValidateMode(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Mode.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("mode")
		}
		return err
	}

	return nil
}

func (m *CoolingZoneSetting) contextValidatePower(ctx context.Context, formats strfmt.Registry) error {

	if m.Power != nil {
		if err := m.Power.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("power")
			}
			return err
		}
	}

	return nil
}

func (m *CoolingZoneSetting) contextValidateSwing(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Swing.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("swing")
		}
		return err
	}

	return nil
}

func (m *CoolingZoneSetting) contextValidateTemperature(ctx context.Context, formats strfmt.Registry) error {

	if m.Temperature != nil {
		if err := m.Temperature.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("temperature")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CoolingZoneSetting) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CoolingZoneSetting) UnmarshalBinary(b []byte) error {
	var res CoolingZoneSetting
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
