// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"io/ioutil"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// GenericZoneCapabilities generic zone capabilities
//
// swagger:discriminator GenericZoneCapabilities type
type GenericZoneCapabilities interface {
	runtime.Validatable
	runtime.ContextValidatable

	// The system type of the zone. Depending on the value of `type`, either `AirConditioningCapabilities`, `HeatingCapabilities` or `HotWaterCapabilities` is returned.
	// Required: true
	Type() TadoSystemType
	SetType(TadoSystemType)

	// AdditionalProperties in base type shoud be handled just like regular properties
	// At this moment, the base type property is pushed down to the subtype
}

type genericZoneCapabilities struct {
	typeField TadoSystemType
}

// Type gets the type of this polymorphic type
func (m *genericZoneCapabilities) Type() TadoSystemType {
	return "GenericZoneCapabilities"
}

// SetType sets the type of this polymorphic type
func (m *genericZoneCapabilities) SetType(_ TadoSystemType) {
}

// UnmarshalGenericZoneCapabilitiesSlice unmarshals polymorphic slices of GenericZoneCapabilities
func UnmarshalGenericZoneCapabilitiesSlice(reader io.Reader, consumer runtime.Consumer) ([]GenericZoneCapabilities, error) {
	var elements []json.RawMessage
	if err := consumer.Consume(reader, &elements); err != nil {
		return nil, err
	}

	var result []GenericZoneCapabilities
	for _, element := range elements {
		obj, err := unmarshalGenericZoneCapabilities(element, consumer)
		if err != nil {
			return nil, err
		}
		result = append(result, obj)
	}
	return result, nil
}

// UnmarshalGenericZoneCapabilities unmarshals polymorphic GenericZoneCapabilities
func UnmarshalGenericZoneCapabilities(reader io.Reader, consumer runtime.Consumer) (GenericZoneCapabilities, error) {
	// we need to read this twice, so first into a buffer
	data, err := ioutil.ReadAll(reader)
	if err != nil {
		return nil, err
	}
	return unmarshalGenericZoneCapabilities(data, consumer)
}

func unmarshalGenericZoneCapabilities(data []byte, consumer runtime.Consumer) (GenericZoneCapabilities, error) {
	buf := bytes.NewBuffer(data)
	buf2 := bytes.NewBuffer(data)

	// the first time this is read is to fetch the value of the type property.
	var getType struct {
		Type string `json:"type"`
	}
	if err := consumer.Consume(buf, &getType); err != nil {
		return nil, err
	}

	if err := validate.RequiredString("type", "body", getType.Type); err != nil {
		return nil, err
	}

	// The value of type is used to determine which type to create and unmarshal the data into
	switch getType.Type {
	case "AirConditioningCapabilities":
		var result AirConditioningCapabilities
		if err := consumer.Consume(buf2, &result); err != nil {
			return nil, err
		}
		return &result, nil
	case "GenericZoneCapabilities":
		var result genericZoneCapabilities
		if err := consumer.Consume(buf2, &result); err != nil {
			return nil, err
		}
		return &result, nil
	case "HeatingCapabilities":
		var result HeatingCapabilities
		if err := consumer.Consume(buf2, &result); err != nil {
			return nil, err
		}
		return &result, nil
	case "HotWaterCapabilities":
		var result HotWaterCapabilities
		if err := consumer.Consume(buf2, &result); err != nil {
			return nil, err
		}
		return &result, nil
	}
	return nil, errors.New(422, "invalid type value: %q", getType.Type)
}

// Validate validates this generic zone capabilities
func (m *genericZoneCapabilities) Validate(_ strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this generic zone capabilities based on the context it is used
func (m *genericZoneCapabilities) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *genericZoneCapabilities) contextValidateType(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Type().ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("type")
		}
		return err
	}

	return nil
}
