// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// HomePresence home presence
//
// swagger:model HomePresence
type HomePresence struct {

	// Presence State.
	// Required: true
	HomePresence *PresenceState `json:"homePresence"`
}

// Validate validates this home presence
func (m *HomePresence) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHomePresence(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HomePresence) validateHomePresence(formats strfmt.Registry) error {

	if err := validate.Required("homePresence", "body", m.HomePresence); err != nil {
		return err
	}

	if err := validate.Required("homePresence", "body", m.HomePresence); err != nil {
		return err
	}

	if m.HomePresence != nil {
		if err := m.HomePresence.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("homePresence")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this home presence based on the context it is used
func (m *HomePresence) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateHomePresence(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HomePresence) contextValidateHomePresence(ctx context.Context, formats strfmt.Registry) error {

	if m.HomePresence != nil {
		if err := m.HomePresence.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("homePresence")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HomePresence) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HomePresence) UnmarshalBinary(b []byte) error {
	var res HomePresence
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
