// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// HotWaterZoneSetting hot water zone setting
//
// swagger:model HotWaterZoneSetting
type HotWaterZoneSetting struct {

	// Whether domestic hot water should be produced or not.
	// Required: true
	Power *Power `json:"power"`

	// The desired hot water temperature, if power is `ON`. Only available if setting a temperature for hot water is supported by the heating setup.
	Temperature *TemperatureObject `json:"temperature,omitempty"`
}

// Type gets the type of this subtype
func (m *HotWaterZoneSetting) Type() TadoSystemType {
	return "HotWaterZoneSetting"
}

// SetType sets the type of this subtype
func (m *HotWaterZoneSetting) SetType(_ TadoSystemType) {
}

// UnmarshalJSON unmarshals this object with a polymorphic type from a JSON structure
func (m *HotWaterZoneSetting) UnmarshalJSON(raw []byte) error {
	var data struct {

		// Whether domestic hot water should be produced or not.
		// Required: true
		Power *Power `json:"power"`

		// The desired hot water temperature, if power is `ON`. Only available if setting a temperature for hot water is supported by the heating setup.
		Temperature *TemperatureObject `json:"temperature,omitempty"`
	}
	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	var base struct {
		/* Just the base type fields. Used for unmashalling polymorphic types.*/

		Type TadoSystemType `json:"type"`
	}
	buf = bytes.NewBuffer(raw)
	dec = json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&base); err != nil {
		return err
	}

	var result HotWaterZoneSetting

	if base.Type != result.Type() {
		/* Not the type we're looking for. */
		return errors.New(422, "invalid type value: %q", base.Type)
	}

	result.Power = data.Power
	result.Temperature = data.Temperature

	*m = result

	return nil
}

// MarshalJSON marshals this object with a polymorphic type to a JSON structure
func (m HotWaterZoneSetting) MarshalJSON() ([]byte, error) {
	var b1, b2, b3 []byte
	var err error
	b1, err = json.Marshal(struct {

		// Whether domestic hot water should be produced or not.
		// Required: true
		Power *Power `json:"power"`

		// The desired hot water temperature, if power is `ON`. Only available if setting a temperature for hot water is supported by the heating setup.
		Temperature *TemperatureObject `json:"temperature,omitempty"`
	}{

		Power: m.Power,

		Temperature: m.Temperature,
	})
	if err != nil {
		return nil, err
	}
	b2, err = json.Marshal(struct {
		Type TadoSystemType `json:"type"`
	}{

		Type: m.Type(),
	})
	if err != nil {
		return nil, err
	}

	return swag.ConcatJSON(b1, b2, b3), nil
}

// Validate validates this hot water zone setting
func (m *HotWaterZoneSetting) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePower(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTemperature(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HotWaterZoneSetting) validatePower(formats strfmt.Registry) error {

	if err := validate.Required("power", "body", m.Power); err != nil {
		return err
	}

	if err := validate.Required("power", "body", m.Power); err != nil {
		return err
	}

	if m.Power != nil {
		if err := m.Power.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("power")
			}
			return err
		}
	}

	return nil
}

func (m *HotWaterZoneSetting) validateTemperature(formats strfmt.Registry) error {

	if swag.IsZero(m.Temperature) { // not required
		return nil
	}

	if m.Temperature != nil {
		if err := m.Temperature.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("temperature")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this hot water zone setting based on the context it is used
func (m *HotWaterZoneSetting) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePower(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTemperature(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HotWaterZoneSetting) contextValidateType(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Type().ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("type")
		}
		return err
	}

	return nil
}

func (m *HotWaterZoneSetting) contextValidatePower(ctx context.Context, formats strfmt.Registry) error {

	if m.Power != nil {
		if err := m.Power.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("power")
			}
			return err
		}
	}

	return nil
}

func (m *HotWaterZoneSetting) contextValidateTemperature(ctx context.Context, formats strfmt.Registry) error {

	if m.Temperature != nil {
		if err := m.Temperature.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("temperature")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HotWaterZoneSetting) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HotWaterZoneSetting) UnmarshalBinary(b []byte) error {
	var res HotWaterZoneSetting
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
