// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ManualTerminationCondition The overlay only terminates when it is manually removed.
//
// swagger:model ManualTerminationCondition
type ManualTerminationCondition struct {
	projectedExpiryField strfmt.DateTime
}

// ProjectedExpiry gets the projected expiry of this subtype
func (m *ManualTerminationCondition) ProjectedExpiry() strfmt.DateTime {
	return m.projectedExpiryField
}

// SetProjectedExpiry sets the projected expiry of this subtype
func (m *ManualTerminationCondition) SetProjectedExpiry(val strfmt.DateTime) {
	m.projectedExpiryField = val
}

// Type gets the type of this subtype
func (m *ManualTerminationCondition) Type() OverlayTerminationConditionType {
	return "ManualTerminationCondition"
}

// SetType sets the type of this subtype
func (m *ManualTerminationCondition) SetType(val OverlayTerminationConditionType) {
}

// UnmarshalJSON unmarshals this object with a polymorphic type from a JSON structure
func (m *ManualTerminationCondition) UnmarshalJSON(raw []byte) error {
	var data struct {
	}
	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	var base struct {
		/* Just the base type fields. Used for unmashalling polymorphic types.*/

		ProjectedExpiry strfmt.DateTime `json:"projectedExpiry,omitempty"`

		Type OverlayTerminationConditionType `json:"type"`
	}
	buf = bytes.NewBuffer(raw)
	dec = json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&base); err != nil {
		return err
	}

	var result ManualTerminationCondition

	result.projectedExpiryField = base.ProjectedExpiry

	if base.Type != result.Type() {
		/* Not the type we're looking for. */
		return errors.New(422, "invalid type value: %q", base.Type)
	}

	*m = result

	return nil
}

// MarshalJSON marshals this object with a polymorphic type to a JSON structure
func (m ManualTerminationCondition) MarshalJSON() ([]byte, error) {
	var b1, b2, b3 []byte
	var err error
	b1, err = json.Marshal(struct {
	}{})
	if err != nil {
		return nil, err
	}
	b2, err = json.Marshal(struct {
		ProjectedExpiry strfmt.DateTime `json:"projectedExpiry,omitempty"`

		Type OverlayTerminationConditionType `json:"type"`
	}{

		ProjectedExpiry: m.ProjectedExpiry(),

		Type: m.Type(),
	})
	if err != nil {
		return nil, err
	}

	return swag.ConcatJSON(b1, b2, b3), nil
}

// Validate validates this manual termination condition
func (m *ManualTerminationCondition) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProjectedExpiry(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ManualTerminationCondition) validateProjectedExpiry(formats strfmt.Registry) error {

	if swag.IsZero(m.ProjectedExpiry()) { // not required
		return nil
	}

	if err := validate.FormatOf("projectedExpiry", "body", "date-time", m.ProjectedExpiry().String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this manual termination condition based on the context it is used
func (m *ManualTerminationCondition) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateProjectedExpiry(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ManualTerminationCondition) contextValidateProjectedExpiry(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "projectedExpiry", "body", strfmt.DateTime(m.ProjectedExpiry())); err != nil {
		return err
	}

	return nil
}

func (m *ManualTerminationCondition) contextValidateType(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Type().ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("type")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ManualTerminationCondition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ManualTerminationCondition) UnmarshalBinary(b []byte) error {
	var res ManualTerminationCondition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
