// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MobileDeviceSettings mobile device settings
//
// swagger:model MobileDeviceSettings
type MobileDeviceSettings struct {

	// Whether this device's location is reported to the server so that this decice participates in the geolocation logic of controlling the home.
	// Required: true
	GeoTrackingEnabled *bool `json:"geoTrackingEnabled"`
}

// Validate validates this mobile device settings
func (m *MobileDeviceSettings) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGeoTrackingEnabled(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MobileDeviceSettings) validateGeoTrackingEnabled(formats strfmt.Registry) error {

	if err := validate.Required("geoTrackingEnabled", "body", m.GeoTrackingEnabled); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this mobile device settings based on context it is used
func (m *MobileDeviceSettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MobileDeviceSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MobileDeviceSettings) UnmarshalBinary(b []byte) error {
	var res MobileDeviceSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
