// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"io/ioutil"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// OverlayTerminationConditionTemplate A template to be used e.g. as a default for an overlay's termination condition. See `OverlayTerminationCondition` definition for more info.
//
// swagger:discriminator OverlayTerminationConditionTemplate type
type OverlayTerminationConditionTemplate interface {
	runtime.Validatable
	runtime.ContextValidatable

	// type
	// Required: true
	Type() OverlayTerminationConditionType
	SetType(OverlayTerminationConditionType)

	// AdditionalProperties in base type shoud be handled just like regular properties
	// At this moment, the base type property is pushed down to the subtype
}

type overlayTerminationConditionTemplate struct {
	typeField OverlayTerminationConditionType
}

// Type gets the type of this polymorphic type
func (m *overlayTerminationConditionTemplate) Type() OverlayTerminationConditionType {
	return "OverlayTerminationConditionTemplate"
}

// SetType sets the type of this polymorphic type
func (m *overlayTerminationConditionTemplate) SetType(_ OverlayTerminationConditionType) {
}

// UnmarshalOverlayTerminationConditionTemplateSlice unmarshals polymorphic slices of OverlayTerminationConditionTemplate
func UnmarshalOverlayTerminationConditionTemplateSlice(reader io.Reader, consumer runtime.Consumer) ([]OverlayTerminationConditionTemplate, error) {
	var elements []json.RawMessage
	if err := consumer.Consume(reader, &elements); err != nil {
		return nil, err
	}

	var result []OverlayTerminationConditionTemplate
	for _, element := range elements {
		obj, err := unmarshalOverlayTerminationConditionTemplate(element, consumer)
		if err != nil {
			return nil, err
		}
		result = append(result, obj)
	}
	return result, nil
}

// UnmarshalOverlayTerminationConditionTemplate unmarshals polymorphic OverlayTerminationConditionTemplate
func UnmarshalOverlayTerminationConditionTemplate(reader io.Reader, consumer runtime.Consumer) (OverlayTerminationConditionTemplate, error) {
	// we need to read this twice, so first into a buffer
	data, err := ioutil.ReadAll(reader)
	if err != nil {
		return nil, err
	}
	return unmarshalOverlayTerminationConditionTemplate(data, consumer)
}

func unmarshalOverlayTerminationConditionTemplate(data []byte, consumer runtime.Consumer) (OverlayTerminationConditionTemplate, error) {
	buf := bytes.NewBuffer(data)
	buf2 := bytes.NewBuffer(data)

	// the first time this is read is to fetch the value of the type property.
	var getType struct {
		Type string `json:"type"`
	}
	if err := consumer.Consume(buf, &getType); err != nil {
		return nil, err
	}

	if err := validate.RequiredString("type", "body", getType.Type); err != nil {
		return nil, err
	}

	// The value of type is used to determine which type to create and unmarshal the data into
	switch getType.Type {
	case "OverlayTerminationConditionTemplate":
		var result overlayTerminationConditionTemplate
		if err := consumer.Consume(buf2, &result); err != nil {
			return nil, err
		}
		return &result, nil
	case "TimerTerminationConditionTemplate":
		var result TimerTerminationConditionTemplate
		if err := consumer.Consume(buf2, &result); err != nil {
			return nil, err
		}
		return &result, nil
	}
	return nil, errors.New(422, "invalid type value: %q", getType.Type)
}

// Validate validates this overlay termination condition template
func (m *overlayTerminationConditionTemplate) Validate(_ strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this overlay termination condition template based on the context it is used
func (m *overlayTerminationConditionTemplate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *overlayTerminationConditionTemplate) contextValidateType(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Type().ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("type")
		}
		return err
	}

	return nil
}
