// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Preparation Contains preparation target if tado is preparing for an upcoming mode, otherwise null.
//
// swagger:model Preparation
type Preparation struct {

	// end
	// Required: true
	// Format: date-time
	End *strfmt.DateTime `json:"end"`

	settingField GenericZoneSetting

	// tado mode
	// Required: true
	TadoMode *TadoMode `json:"tadoMode"`
}

// Setting gets the setting of this base type
func (m *Preparation) Setting() GenericZoneSetting {
	return m.settingField
}

// SetSetting sets the setting of this base type
func (m *Preparation) SetSetting(val GenericZoneSetting) {
	m.settingField = val
}

// UnmarshalJSON unmarshals this object with a polymorphic type from a JSON structure
func (m *Preparation) UnmarshalJSON(raw []byte) error {
	var data struct {
		End *strfmt.DateTime `json:"end"`

		Setting json.RawMessage `json:"setting"`

		TadoMode *TadoMode `json:"tadoMode"`
	}
	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	propSetting, err := UnmarshalGenericZoneSetting(bytes.NewBuffer(data.Setting), runtime.JSONConsumer())
	if err != nil && err != io.EOF {
		return err
	}

	var result Preparation

	// end
	result.End = data.End

	// setting
	result.settingField = propSetting

	// tadoMode
	result.TadoMode = data.TadoMode

	*m = result

	return nil
}

// MarshalJSON marshals this object with a polymorphic type to a JSON structure
func (m Preparation) MarshalJSON() ([]byte, error) {
	var b1, b2, b3 []byte
	var err error
	b1, err = json.Marshal(struct {
		End *strfmt.DateTime `json:"end"`

		TadoMode *TadoMode `json:"tadoMode"`
	}{

		End: m.End,

		TadoMode: m.TadoMode,
	})
	if err != nil {
		return nil, err
	}
	b2, err = json.Marshal(struct {
		Setting GenericZoneSetting `json:"setting"`
	}{

		Setting: m.settingField,
	})
	if err != nil {
		return nil, err
	}

	return swag.ConcatJSON(b1, b2, b3), nil
}

// Validate validates this preparation
func (m *Preparation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEnd(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSetting(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTadoMode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Preparation) validateEnd(formats strfmt.Registry) error {

	if err := validate.Required("end", "body", m.End); err != nil {
		return err
	}

	if err := validate.FormatOf("end", "body", "date-time", m.End.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Preparation) validateSetting(formats strfmt.Registry) error {

	if err := validate.Required("setting", "body", m.Setting()); err != nil {
		return err
	}

	if err := m.Setting().Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("setting")
		}
		return err
	}

	return nil
}

func (m *Preparation) validateTadoMode(formats strfmt.Registry) error {

	if err := validate.Required("tadoMode", "body", m.TadoMode); err != nil {
		return err
	}

	if err := validate.Required("tadoMode", "body", m.TadoMode); err != nil {
		return err
	}

	if m.TadoMode != nil {
		if err := m.TadoMode.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tadoMode")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this preparation based on the context it is used
func (m *Preparation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSetting(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTadoMode(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Preparation) contextValidateSetting(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Setting().ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("setting")
		}
		return err
	}

	return nil
}

func (m *Preparation) contextValidateTadoMode(ctx context.Context, formats strfmt.Registry) error {

	if m.TadoMode != nil {
		if err := m.TadoMode.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tadoMode")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Preparation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Preparation) UnmarshalBinary(b []byte) error {
	var res Preparation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
