// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TemperatureObject A temperature specified in degrees celsius and fahrenheit.
//
// swagger:model TemperatureObject
type TemperatureObject struct {

	// The temperature in celsius.
	Celsius float32 `json:"celsius,omitempty"`

	// The temperature in fahrenheit.
	Fahrenheit float32 `json:"fahrenheit,omitempty"`
}

// Validate validates this temperature object
func (m *TemperatureObject) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this temperature object based on context it is used
func (m *TemperatureObject) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TemperatureObject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TemperatureObject) UnmarshalBinary(b []byte) error {
	var res TemperatureObject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
