// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TimerTerminationConditionTemplate timer termination condition template
//
// swagger:model TimerTerminationConditionTemplate
type TimerTerminationConditionTemplate struct {

	// The number of seconds that the overlay should last/was configured to last.
	// Required: true
	// Minimum: 0
	DurationInSeconds *int64 `json:"durationInSeconds"`
}

// Type gets the type of this subtype
func (m *TimerTerminationConditionTemplate) Type() OverlayTerminationConditionType {
	return "TimerTerminationConditionTemplate"
}

// SetType sets the type of this subtype
func (m *TimerTerminationConditionTemplate) SetType(val OverlayTerminationConditionType) {
}

// UnmarshalJSON unmarshals this object with a polymorphic type from a JSON structure
func (m *TimerTerminationConditionTemplate) UnmarshalJSON(raw []byte) error {
	var data struct {

		// The number of seconds that the overlay should last/was configured to last.
		// Required: true
		// Minimum: 0
		DurationInSeconds *int64 `json:"durationInSeconds"`
	}
	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	var base struct {
		/* Just the base type fields. Used for unmashalling polymorphic types.*/

		Type OverlayTerminationConditionType `json:"type"`
	}
	buf = bytes.NewBuffer(raw)
	dec = json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&base); err != nil {
		return err
	}

	var result TimerTerminationConditionTemplate

	if base.Type != result.Type() {
		/* Not the type we're looking for. */
		return errors.New(422, "invalid type value: %q", base.Type)
	}

	result.DurationInSeconds = data.DurationInSeconds

	*m = result

	return nil
}

// MarshalJSON marshals this object with a polymorphic type to a JSON structure
func (m TimerTerminationConditionTemplate) MarshalJSON() ([]byte, error) {
	var b1, b2, b3 []byte
	var err error
	b1, err = json.Marshal(struct {

		// The number of seconds that the overlay should last/was configured to last.
		// Required: true
		// Minimum: 0
		DurationInSeconds *int64 `json:"durationInSeconds"`
	}{

		DurationInSeconds: m.DurationInSeconds,
	})
	if err != nil {
		return nil, err
	}
	b2, err = json.Marshal(struct {
		Type OverlayTerminationConditionType `json:"type"`
	}{

		Type: m.Type(),
	})
	if err != nil {
		return nil, err
	}

	return swag.ConcatJSON(b1, b2, b3), nil
}

// Validate validates this timer termination condition template
func (m *TimerTerminationConditionTemplate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDurationInSeconds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TimerTerminationConditionTemplate) validateDurationInSeconds(formats strfmt.Registry) error {

	if err := validate.Required("durationInSeconds", "body", m.DurationInSeconds); err != nil {
		return err
	}

	if err := validate.MinimumInt("durationInSeconds", "body", *m.DurationInSeconds, 0, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this timer termination condition template based on the context it is used
func (m *TimerTerminationConditionTemplate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TimerTerminationConditionTemplate) contextValidateType(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Type().ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("type")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TimerTerminationConditionTemplate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TimerTerminationConditionTemplate) UnmarshalBinary(b []byte) error {
	var res TimerTerminationConditionTemplate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
